### ISSUE TITLE
README.md label build result

### ISSUE THREAD

**Issue by lauracosta** [ARPA-SIMC/agroTools#2]
Ho inserito i link nel README affinchè mostrino il risultato del build. Il link porta correttamente alla pagina di Travis, ma il risultato della compilazione non è quello atteso. Resta in error quando dovrebbe diventare passed. Cosa sbaglio?

**Comment by lauracosta** [comment]
Ok penso sia legato al fatto che ho rinominato il nome del branch in master per uniformità con tutti gli altri (ed a quello faranno quindi riferimento i link nel readme) ma in travis resta Default Branch: main (il nome precedente). Andrebbe allineato ma non credo di poterlo fare, o almeno non ci riesco.

**Comment by brancomat** [comment]
Da quel che vedo io i link ora risultano allineati e il default branch di travis è master:
![image](https://user-images.githubusercontent.com/13255425/112175509-9650e900-8bf7-11eb-8898-16cee08cd115.png)

**Comment by lauracosta** [comment]
Ho modificato il trigger build, pare sia ok ora come mostri tu. Però continuo a non vedere le label aggiornate con il risultato corretto.

**Comment by brancomat** [comment]
Può essere un problema di cache del browser? Io li vedo correttamente:
![image](https://user-images.githubusercontent.com/13255425/112177929-a4076e00-8bf9-11eb-9f1b-94a63057bedc.png)

(prima dell'ultimo commit mostravano i risultati dei rispettivi build)

**Comment by lauracosta** [comment]
Ok tutto andato a posto, grazie!
