### ISSUE TITLE
 abilitare token per caricare rpm su copr 

### ISSUE THREAD

**Issue by lauracosta** [ARPA-SIMC/agroTools#3]
Can't open .copr.enc for reading, No such file or directory

**Comment by brancomat** [comment]
Aggiunto token copr.

**Comment by lauracosta** [comment]
Ho riprovato a fare il tag ma ottengo ancora errore
$ openssl aes-256-cbc -K $encrypted_dd0997aeff41_key -iv $encrypted_dd0997aeff41_iv -in .copr.enc -out .copr -d

Can't open .copr.enc for reading, No such file or directory

**Comment by edigiacomo** [comment]
Mancava il file `.copr.enc`, vediamo se adesso funziona.

**Comment by lauracosta** [comment]
Grazie!

**Comment by lauracosta** [comment]
La stringa cifrata presente nel file travis.yml di agroTools 
api_key:
    secure:
è la stessa di quella presente nel file travis.yml di CRITERIA1D (mentre il repos PRAGA ha una stringa differente). Immagino debba essere in qualche modo aggiornata.
Potrebbe essere causa del failed del caricamento su GitHub della nuova release nella compilazione xenial?
Riporto l'errore:
https://api.github.com/user: 401 - Bad credentials // See: https://docs.github.com/rest (Octokit::Unauthorized)

**Comment by edigiacomo** [comment]
Mi pare un errore relativo a delle API di GitHub, quindi non Travis o Copr, che sono servizi terzi. Mi potresti linkare i log in cui hai l'errore?

**Comment by edigiacomo** [comment]
Ok, ho capito da solo: stai parlando del token per le release dei file appimage su github, che è un ambito diverso da quello per l'invio a Copr, apro issue nuova.
