### ISSUE TITLE
Abilitare Travis a effettuare le release

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/agroTools#4]
Si deve creare un OAuth token di GitHub per permette l'upload dei file di AppImage nelle release da parte di Travis (https://docs.travis-ci.com/user/deployment/releases/#using-travis-ci-client-to-populate-initial-deployment-configuration)

**Comment by edigiacomo** [comment]
Il comando necessario per generare il token `travis setup releases` usa una API di GitHub non più supportata e quindi non si riesce a fare login (travis-ci/travis.rb#793). Il workaround suggerito non funziona.

**Comment by ftomei** [comment]
le appImage in questa distribuzione non sono particolarmente necessarie (sono software ad uso prevalentemente interno) quindi si può eliminare l'upload dei file nelle release. E' importante invece che funzioni il deploy su otto

**Comment by edigiacomo** [comment]
Perfetto, ho rimosso l'upload di appimage c35f4da0662ed430add926aa34abd1a61c6a589e
